// @vitest-environment node
/**
 * Derivation test vectors (task 0.5 acceptance).
 * Uses the standard BIP39 test mnemonic — a publicly known phrase that must
 * never hold funds. ETH and BTC vectors are external ground truth (BIP44 /
 * BIP84 reference vectors); SOL/TRX/TON are snapshots generated by this
 * codebase and pinned so any accidental change to derivation logic fails CI.
 *
 * Runs in the node environment: ethers' mnemonic code breaks under the
 * jsdom realm (Buffer fails the cross-realm Uint8Array instanceof check).
 */
import { describe, it, expect, beforeAll } from 'vitest';
import { importWalletFromMnemonic, validateMnemonic, type CryptoWallet } from '@/lib/crypto/wallet';
import { decryptBytes } from '@/lib/crypto/aes';

const TEST_MNEMONIC =
  'abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about';
const PASSWORD = 'test-password-123';
const SLOW = 180_000;

// External reference vectors:
const ETH_VECTOR = '0x9858EfFD232B4033E47d90003D41EC34EcaEda94'; // BIP44 m/44'/60'/0'/0/0
const BTC_VECTOR = 'bc1qcr8te4kr609gcawutmrza0j4xv80jy8z306fyu'; // BIP84 m/84'/0'/0'/0/0

let w: CryptoWallet;

beforeAll(async () => {
  w = await importWalletFromMnemonic(TEST_MNEMONIC, PASSWORD);
}, SLOW);

describe('multi-chain derivation vectors', () => {
  it('validates the test mnemonic', () => {
    expect(validateMnemonic(TEST_MNEMONIC)).toBe(true);
    expect(validateMnemonic('not a valid phrase at all')).toBe(false);
  });

  it('ETH matches the external BIP44 vector', () => {
    expect(w.eth).toBe(ETH_VECTOR);
  });

  it('BTC matches the external BIP84 native SegWit vector', () => {
    expect(w.btc).toBe(BTC_VECTOR);
  });

  it('SOL/TRX/TON match pinned snapshots and format', () => {
    expect(w.sol).toMatch(/^[1-9A-HJ-NP-Za-km-z]{32,44}$/);
    expect(w.tron).toMatch(/^T[1-9A-HJ-NP-Za-km-z]{33}$/);
    expect(w.ton).toMatch(/^[A-Za-z0-9_-]{48}$/);
    // SOL matches the public Phantom vector for this mnemonic (m/44'/501'/0'/0'),
    // TRX matches the public TronLink vector (m/44'/195'/0'/0/0).
    // TON is a pinned snapshot of this codebase's SLIP-0010 m/44'/607'/0'/0'
    // derivation (TON wallets differ in schemes; ours is fixed here, 2026-07-02).
    expect([w.sol, w.tron, w.ton]).toEqual([
      'HAgk14JpMQLgt6rVgv7cBQFJWFto5Dqxi472uT3DKpqk',
      'TUEZSdKsoDHQMeZwihtdoBiN46zxhGWYdH',
      'EQA2qqtv2MASYNxCAjSB740ly2JELsh56uWl1rBeH4jWIs5v',
    ]);
  });

  it('per-chain encrypted blobs decrypt back to 32-byte keys', async () => {
    for (const blob of [w.solEnc, w.btcEnc, w.tronEnc, w.tonEnc]) {
      const key = await decryptBytes(blob, PASSWORD);
      expect(key.length).toBe(32);
      key.fill(0);
    }
  });

  it('wallet object carries no XOR-scheme fields (removed in 4b3704e)', () => {
    expect(Object.keys(w).filter((k) => k.toLowerCase().includes('xor'))).toEqual([]);
  });
});
