// @vitest-environment node
/**
 * Derivation test vectors (task 0.5 acceptance).
 * Uses the standard BIP39 test mnemonic — a publicly known phrase that must
 * never hold funds. ETH and BTC vectors are external ground truth (BIP44 /
 * BIP84 reference vectors); SOL/TRX/TON are snapshots generated by this
 * codebase and pinned so any accidental change to derivation logic fails CI.
 *
 * Runs in the node environment: ethers' mnemonic code breaks under the
 * jsdom realm (Buffer fails the cross-realm Uint8Array instanceof check).
 */
import { describe, it, expect, beforeAll } from 'vitest';
import { importWalletFromMnemonic, validateMnemonic, type CryptoWallet } from '@/lib/crypto/wallet';
import { decryptBytes } from '@/lib/crypto/aes';
import { tonAddressFromPrivKey } from '@/lib/crypto/ton-tx';
import { mnemonicValidate, mnemonicToPrivateKey } from '@ton/crypto';
import { Address, WalletContractV4 } from '@ton/ton';
import { ethers } from 'ethers';

const TEST_MNEMONIC =
  'abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about';
const PASSWORD = 'test-password-123';
const SLOW = 180_000;

// External reference vectors:
const ETH_VECTOR = '0x9858EfFD232B4033E47d90003D41EC34EcaEda94'; // BIP44 m/44'/60'/0'/0/0
const BTC_VECTOR = 'bc1qcr8te4kr609gcawutmrza0j4xv80jy8z306fyu'; // BIP84 m/84'/0'/0'/0/0

let w: CryptoWallet;

beforeAll(async () => {
  w = await importWalletFromMnemonic(TEST_MNEMONIC, PASSWORD);
}, SLOW);

describe('multi-chain derivation vectors', () => {
  it('validates the test mnemonic', () => {
    expect(validateMnemonic(TEST_MNEMONIC)).toBe(true);
    expect(validateMnemonic('not a valid phrase at all')).toBe(false);
  });

  it('ETH matches the external BIP44 vector', () => {
    expect(w.eth).toBe(ETH_VECTOR);
  });

  it('BTC matches the external BIP84 native SegWit vector', () => {
    expect(w.btc).toBe(BTC_VECTOR);
  });

  it('SOL/TRX/TON match pinned snapshots and format', () => {
    expect(w.sol).toMatch(/^[1-9A-HJ-NP-Za-km-z]{32,44}$/);
    expect(w.tron).toMatch(/^T[1-9A-HJ-NP-Za-km-z]{33}$/);
    expect(w.ton).toMatch(/^[A-Za-z0-9_-]{48}$/);
    // SOL matches the public Phantom vector for this mnemonic (m/44'/501'/0'/0'),
    // TRX matches the public TronLink vector (m/44'/195'/0'/0/0).
    // TON is a pinned snapshot of this codebase's SLIP-0010 m/44'/607'/0'/0'
    // derivation (TON wallets differ in schemes; ours is fixed here, 2026-07-02).
    expect([w.sol, w.tron, w.ton]).toEqual([
      'HAgk14JpMQLgt6rVgv7cBQFJWFto5Dqxi472uT3DKpqk',
      'TUEZSdKsoDHQMeZwihtdoBiN46zxhGWYdH',
      'EQA2qqtv2MASYNxCAjSB740ly2JELsh56uWl1rBeH4jWIs5v',
    ]);
  });

  it(
    'per-chain encrypted blobs decrypt back to 32-byte keys',
    async () => {
      for (const blob of [w.solEnc, w.btcEnc, w.tronEnc, w.tonEnc]) {
        const key = await decryptBytes(blob, PASSWORD);
        expect(key.length).toBe(32);
        key.fill(0);
      }
    },
    SLOW, // 4×PBKDF2-600k под параллельной нагрузкой полного прогона
  );

  it('wallet object carries no XOR-scheme fields (removed in 4b3704e)', () => {
    expect(Object.keys(w).filter((k) => k.toLowerCase().includes('xor'))).toEqual([]);
  });
});

// ─── 24-word dual-valid (BIP39 + TON) vector — DECISION_TON_DERIVATION.md ────
// Generated once and pinned; a test phrase that must never hold funds.
// TON is checked against the TON reference implementation (@ton/crypto
// mnemonicToPrivateKey + V4R2) computed independently of lib/crypto/wallet.ts —
// i.e. the address Tonkeeper derives from this phrase. ETH against ethers.
const DUAL_MNEMONIC =
  'sword tattoo water unknown claw drill evoke circle cannon soccer defense agent ' +
  'vivid bulb awkward raise extend amount honey picnic flat deny ten awake';

describe('24-word dual-valid vector (TON standard scheme)', () => {
  let d: CryptoWallet;
  beforeAll(async () => {
    delete process.env.NEXT_PUBLIC_TON_MNEMONIC_ENABLED;
    d = await importWalletFromMnemonic(DUAL_MNEMONIC, PASSWORD);
  }, SLOW);

  it('phrase is valid both as BIP39 and as a TON mnemonic', async () => {
    expect(validateMnemonic(DUAL_MNEMONIC)).toBe(true);
    expect(await mnemonicValidate(DUAL_MNEMONIC.split(' '))).toBe(true);
  });

  it('TON uses the Tonkeeper scheme and matches the @ton/crypto reference', async () => {
    const kp = await mnemonicToPrivateKey(DUAL_MNEMONIC.split(' '));
    const ref = WalletContractV4.create({ publicKey: kp.publicKey, workchain: 0 }).address;
    expect(d.tonScheme).toBe('ton-mnemonic-v4r2');
    expect(Address.parse(d.ton).equals(ref)).toBe(true);
    expect(d.ton).toBe('EQCdomz4v6wzHIlFIsjr_OMwqHUSZHWai1tfLSRzf7trcR0l');
  });

  it('other chains keep their BIP39 paths (unchanged scheme)', () => {
    expect(d.eth).toBe(ethers.HDNodeWallet.fromPhrase(DUAL_MNEMONIC, '', "m/44'/60'/0'/0/0").address);
    expect([d.eth, d.btc, d.sol, d.tron]).toEqual([
      '0x81c4309B2EA4dD44ADb22d16D81c2ba5AC453463',
      'bc1q2ne2ue8r4jafda4xphn4tgnvr5edslqxnu9lsm',
      'GzrLaQPndWKJGPiTm7mzZ1DfHihfLF1o8sDew5dr12hL',
      'TSnxXVXLjy2EMwKXXg2n6RXkay3cnj5HSc',
    ]);
  });

  it('encrypted TON blob is the signing seed for the same address (send path)', async () => {
    const seed = await decryptBytes(d.tonEnc, PASSWORD);
    expect(seed.length).toBe(32);
    expect(Address.parse(tonAddressFromPrivKey(seed)).equals(Address.parse(d.ton))).toBe(true);
    seed.fill(0);
  }, SLOW);
});

describe('legacy 12-word regression (flag ON must not move the TON address)', () => {
  it('12-word import keeps the legacy SLIP-0010 TON account, shown as UQ…', async () => {
    process.env.NEXT_PUBLIC_TON_MNEMONIC_ENABLED = 'true';
    try {
      const l = await importWalletFromMnemonic(TEST_MNEMONIC, PASSWORD);
      expect(l.tonScheme).toBe('slip10-607-0-0');
      expect(l.ton).toBe('UQA2qqtv2MASYNxCAjSB740ly2JELsh56uWl1rBeH4jWIpOq');
      expect(Address.parse(l.ton).equals(Address.parse('EQA2qqtv2MASYNxCAjSB740ly2JELsh56uWl1rBeH4jWIs5v'))).toBe(true);
    } finally {
      delete process.env.NEXT_PUBLIC_TON_MNEMONIC_ENABLED;
    }
  }, SLOW);

  it('flag OFF: 12-word import is byte-identical to before (legacy scheme, EQ…)', () => {
    expect(w.tonScheme).toBe('slip10-607-0-0');
    expect(w.ton).toBe('EQA2qqtv2MASYNxCAjSB740ly2JELsh56uWl1rBeH4jWIs5v');
  });
});

