/**
 * lib/crypto/btc-tx.ts
 * Bitcoin transaction helpers backed by bitcoinjs-lib PSBT.
 *
 * Supports:
 * - source wallets generated by NeuroWallet: legacy P2PKH (old) and native SegWit P2WPKH (new)
 * - recipient outputs: bc1q, bc1p, 3..., 1...
 */

import * as bitcoin from 'bitcoinjs-lib';
import { ECPairFactory, type ECPairInterface } from 'ecpair';
import * as ecc from 'tiny-secp256k1';
import { Buffer } from 'buffer';

const BLOCKSTREAM = 'https://blockstream.info/api';
const MEMPOOL     = 'https://mempool.space/api';
const NETWORK     = bitcoin.networks.bitcoin;
const ECPair      = ECPairFactory(ecc);

bitcoin.initEccLib(ecc);

export interface UTXO {
  txid:   string;
  vout:   number;
  value:  number; // satoshis
  status: { confirmed: boolean; block_height?: number };
}

type BtcSourceType = 'p2wpkh' | 'p2pkh';

interface SelectedUTXOs {
  utxos:    UTXO[];
  totalIn:  bigint;
  fee:      bigint;
  change:   bigint;
}

function keyPairFromPrivKey(privKey: Uint8Array): ECPairInterface {
  return ECPair.fromPrivateKey(Buffer.from(privKey), { compressed: true, network: NETWORK });
}

function getSourceType(address: string): BtcSourceType {
  if (/^bc1q/i.test(address)) return 'p2wpkh';
  if (/^1/.test(address)) return 'p2pkh';
  throw new Error('Этот тип BTC-адреса отправителя пока не поддерживается. Создай или импортируй обычный NeuroWallet BTC-кошелёк.');
}

function getOwnPayment(keyPair: ECPairInterface, sourceType: BtcSourceType): bitcoin.Payment {
  const pubkey = Buffer.from(keyPair.publicKey);
  if (sourceType === 'p2wpkh') {
    return bitcoin.payments.p2wpkh({ pubkey, network: NETWORK });
  }
  return bitcoin.payments.p2pkh({ pubkey, network: NETWORK });
}

export function btcSegwitAddressFromPrivKey(privKey: Uint8Array): string {
  const keyPair = keyPairFromPrivKey(privKey);
  const payment = bitcoin.payments.p2wpkh({
    pubkey: Buffer.from(keyPair.publicKey),
    network: NETWORK,
  });
  if (!payment.address) throw new Error('Не удалось создать BTC SegWit-адрес.');
  return payment.address;
}

export function isValidBtcAddress(address: string): boolean {
  if (!address) return false;
  try {
    bitcoin.address.toOutputScript(address, NETWORK);
    return /^(bc1q|bc1p|1|3)/i.test(address);
  } catch {
    return false;
  }
}

export async function fetchUTXOs(address: string): Promise<UTXO[]> {
  const res = await fetch(`${BLOCKSTREAM}/address/${address}/utxo`);
  if (!res.ok) throw new Error('Не удалось получить UTXO (Blockstream недоступен).');
  const data = await res.json() as UTXO[];
  return data.filter((u) => u.status.confirmed);
}

export async function getBtcFeeRate(): Promise<number> {
  try {
    const res = await fetch(`${MEMPOOL}/v1/fees/recommended`);
    const data = await res.json() as { hourFee?: number };
    return Math.max(data.hourFee ?? 10, 2);
  } catch {
    return 15;
  }
}

async function fetchRawTx(txid: string): Promise<Buffer> {
  const res = await fetch(`${BLOCKSTREAM}/tx/${txid}/hex`);
  if (!res.ok) throw new Error('Не удалось получить raw BTC transaction для подписи.');
  const hex = await res.text();
  return Buffer.from(hex.trim(), 'hex');
}

export async function broadcastBtcTx(rawHex: string): Promise<string> {
  const res = await fetch(`${BLOCKSTREAM}/tx`, {
    method: 'POST',
    headers: { 'Content-Type': 'text/plain' },
    body: rawHex,
  });
  if (!res.ok) {
    const text = await res.text();
    throw new Error('Blockstream broadcast error: ' + text.slice(0, 200));
  }
  return await res.text();
}

function outputVBytes(address: string): number {
  const script = bitcoin.address.toOutputScript(address, NETWORK);
  return 8 + 1 + script.length;
}

function estimateTxVBytes(inputCount: number, sourceType: BtcSourceType, toAddress: string, changeAddress: string): number {
  const inputVBytes = sourceType === 'p2wpkh' ? 68 : 148;
  return 10 + inputCount * inputVBytes + outputVBytes(toAddress) + outputVBytes(changeAddress);
}

function selectUTXOs(
  available: UTXO[],
  amountSat: bigint,
  feeRateSat: number,
  sourceType: BtcSourceType,
  toAddress: string,
  changeAddress: string,
): SelectedUTXOs {
  const sorted = [...available].sort((a, b) => b.value - a.value);
  const selected: UTXO[] = [];
  let totalIn = 0n;

  for (const utxo of sorted) {
    selected.push(utxo);
    totalIn += BigInt(utxo.value);

    const fee = BigInt(Math.ceil(estimateTxVBytes(selected.length, sourceType, toAddress, changeAddress) * feeRateSat));
    if (totalIn >= amountSat + fee) {
      const change = totalIn - amountSat - fee;
      return { utxos: selected, totalIn, fee, change };
    }
  }

  const fee = BigInt(Math.ceil(estimateTxVBytes(Math.max(selected.length, 1), sourceType, toAddress, changeAddress) * feeRateSat));
  throw new Error(
    `Недостаточно средств. Доступно: ${Number(totalIn) / 1e8} BTC, нужно: ${Number(amountSat + fee) / 1e8} BTC (включая комиссию).`
  );
}

export async function buildSignedTx(
  privKey:       Uint8Array,
  utxos:         UTXO[],
  toAddress:     string,
  changeAddress: string,
  amountSat:     bigint,
  feeRateSat:    number,
): Promise<string> {
  const sourceType = getSourceType(changeAddress);
  const keyPair    = keyPairFromPrivKey(privKey);
  const payment    = getOwnPayment(keyPair, sourceType);
  if (!payment.output) throw new Error('Не удалось создать BTC input script.');

  const selected = selectUTXOs(utxos, amountSat, feeRateSat, sourceType, toAddress, changeAddress);
  const psbt = new bitcoin.Psbt({ network: NETWORK });

  for (const utxo of selected.utxos) {
    if (sourceType === 'p2wpkh') {
      psbt.addInput({
        hash: utxo.txid,
        index: utxo.vout,
        witnessUtxo: {
          script: payment.output,
          value: BigInt(utxo.value),
        },
      });
    } else {
      psbt.addInput({
        hash: utxo.txid,
        index: utxo.vout,
        nonWitnessUtxo: await fetchRawTx(utxo.txid),
      });
    }
  }

  psbt.addOutput({ address: toAddress, value: amountSat });
  if (selected.change > 546n) {
    psbt.addOutput({ address: changeAddress, value: selected.change });
  }

  psbt.signAllInputs(keyPair);
  psbt.finalizeAllInputs();
  return psbt.extractTransaction().toHex();
}
